const actionTypes = {
  SORT_BY_PRICE: 'SORT_BY_PRICE',
  SORT_BY_TIME: 'SORT_BY_TIME',
  SORT_BY_AVERAGE: 'SORT_BY_AVERAGE',
  FILTER_ALL_TRANSFERS: 'FILTER_ALL_TRANSFERS',
  FILTER_ON_TRANSFERS: 'FILTER_ON_TRANSFERS',
  FILTER_ONE_TRANSFERS: 'FILTER_ONE_TRANSFERS',
  FILTER_TWO_TRANSFERS: 'FILTER_TWO_TRANSFERS',
  FILTER_THREE_TRANSFERS: 'FILTER_THREE_TRANSFERS',
  STOP_RECEIVING: 'STOP_RECEIVING',
  BUTTON_SHOW_ALL: 'BUTTON_SHOW_ALL',
  TICKET_DATA_SUCCESS: 'TICKET_DATA_SUCCESS',
};
export default actionTypes;
